Net: # ["FSANET", "ResNet"]
  net_type: "FSANET" 
  n_class: "3"

Data: # ["BIWI", "AFLW2000", "300WLP"]
  train_dir: "/media/2tb/projects/VL's/headpose_data"
  train_name: "CMU_dataset_64x64"
  train_type: "HDF5_multi"

  val_dir: "/media/2tb/projects/VL's/headpose_data"
  val_name: "aflw2000_filename.txt"
  val_type: "AFLW2000"

  # # "ResNet"
  # target_size: 224
  # "FSANET"
  target_size: 64
  num_worker: 1

Train:
  num_epoch: 90
  batch_size: 128
  val_every: 1
  val_every: 1
  resume: True
  pretrained_path: "/media/2tb/projects/VL's/FSANet/models/fsanet_MSE_HDF5_CMU_300WLP/checkpoint_epoch_59_11.317944586277008.pth"
  saved_dir: "/media/2tb/projects/VL's/FSANet"
  loss_type: "MSE" # ["RANK", "MSE"]
  optimizer:
    mode: "adam"
    base_lr: 0.00001
    t_max: 10

Evaluate:
  eval_dir: "/media/2tb/projects/VL's/FSANet"
  eval_name: "biwi_dataset_list.txt"
  eval_type: "BIWI"

