Net: # ["FSANET", "ResNet"]
  net_type: "FSANET" 
  n_class: "3"

Data: # ["BIWI", "AFLW2000", "300WLP"]
  train_dir: "/content/fsanet_pytorch/data"
  train_name: "300W_LP_dataset_122450_64x64.hdf5"
  train_type: "300W_LP_HDF5"

  val_dir: "/content/fsanet_pytorch/data"
  val_name: "aflw2000_filename.txt"
  val_type: "AFLW2000"

  # # "ResNet"
  # target_size: 224
  # "FSANET"
  target_size: 64
  num_worker: 4

Train:
  num_epoch: 90
  batch_size: 64
  val_every: 5
  resume: True
  pretrained_path: "/content/drive/MyDrive/Colab Notebooks/FSANet/models/headpose_fsanet_mse_colab/checkpoint_epoch_40_5.494957804679871.pth"
  saved_dir: "/content/drive/MyDrive/Colab Notebooks/FSANet"
  loss_type: "MSE" # ["RANK", "MSE"]
  optimizer:
    mode: "adam"
    base_lr: 0.0001
    t_max: 10

Evaluate:
  eval_dir: "/home/linhnv/projects/RankPose/data"
  eval_name: "biwi_dataset_list.txt"
  eval_type: "BIWI"

