Net: # ["FSANET", "ResNet"]
  net_type: "Perceiver" 
  n_class: "3"

Data: # ["BIWI", "AFLW2000", "300WLP"]
  # train_dir: "/home/linhnv/Downloads/headpose_data_300WLP"
  train_dir: "/media/2tb/projects/VL's/headpose_data/headpose_data_300WLP_AFLW2000/headpose_data_300WLP"
  train_name: "CMU_dataset_64x64"
  train_type: "HDF5_multi"

  val_dir: "/media/2tb/projects/VL's/headpose_data/headpose_data_300WLP_AFLW2000/headpose_data_300WLP"
  val_name: "aflw2000_filename.txt"
  val_type: "AFLW2000"

  # # "ResNet"
  # target_size: 224
  # "FSANET"
  target_size: 64
  num_worker: 1

Train:
  num_epoch: 600
  batch_size: 128
  val_every: 1
  val_every: 1
  resume: False
  # pretrained_path: "/media/2tb/projects/VL's/FSANet/models/fsanet_MSE_HDF5_top_CMU_300WLP/checkpoint_epoch_105_11.40754383802414.pth"
  pretrained_path: "/media/2tb/projects/VL's/FSANet/models/perceiver_MSE_HDF5__300WLP/checkpoint_epoch_99_11.950870633125305.pth"
  saved_dir: "/media/2tb/projects/VL's/FSANet"
  loss_type: "MSE" # ["RANK", "MSE"]
  optimizer:
    mode: "adam"
    base_lr: 0.0005
    t_max: 10

Evaluate:
  eval_dir: "/media/2tb/projects/VL's/FSANet"
  eval_name: "biwi_dataset_list.txt"
  eval_type: "BIWI"

